# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
      host: localhost
      adapter: mysql2
      database: pro
      port: 3000
      username: root
      password: s@ntosh

test: &test
      host: localhost
      adapter: mysql2
      database: pro
      port: 3000
      username: root
      password: s@ntosh

production:
      host: localhost
      adapter: mysql2
      database: pro
      port: 3000
      username: root
      password: s@ntosh